### ISSUE TITLE
protoc-bundled plugin should support newer protoc versions

### ISSUE THREAD

**Issue by hgschmie** [comoyo/commons#34]
2.6.1 and 3.0.0 seem to be missing. Support for those would be great.

**Comment by argggh** [comment]
3.0.0 does not appear to be released in final form yet.  Could you have a look at the 2.6.1 binaries in #35 and verify that the relevant versions work for you?  Thanks!

**Comment by mikesamuel** [comment]
https://github.com/comoyo/commons/pull/41 adds support for 3.0.0
